# Generated by Django 4.1.6 on 2023-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_feature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="feature_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
